version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

    command: ["./binar"]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dinaisthebest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    #command: ["-path", "/migrations", "-database", "postgres://postgres:dinaisthebest@db:5432/postgres?sslmode=disable", "down", "-all"]
    command: ["-path", "/migrations", "-database", "postgres://postgres:dinaisthebest@db:5432/postgres?sslmode=disable", "up"]
    depends_on:
      - db
    volumes:
      - ./pkg/dinapp/migrations:/migrations


volumes:
  pgdata: